name: translate
description: "A production-grade translation app for Ugandan languages."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # --- UI & Icons ---
  cupertino_icons: ^1.0.8
  intl: ^0.20.2

  # --- Architecture & State Management ---
  # 'provider': Used for dependency injection and state management (Clean Architecture Presentation Layer)
  provider: ^6.1.2

  # 'equatable': Simplifies object comparison in the Domain Layer (Entities)
  equatable: ^2.0.7

  # 'go_router': Production-grade navigation (Deep linking, Auth redirects)
  go_router: ^14.2.0

  # --- Firebase & Backend ---
  # 'firebase_core': The bridge between Flutter and Firebase
  firebase_core: ^3.1.0

  # 'cloud_firestore': Storing translation data and ML metadata
  cloud_firestore: ^5.0.1

  # 'firebase_auth': Managing users (Critical for tracking who submitted what translation)
  firebase_auth: ^5.1.0

  # 'google_sign_in': For the "Continue with Google" button in your UI
  google_sign_in: ^6.2.1

  # --- Local Storage ---
  # 'shared_preferences': For saving local settings (Theme, Notification toggles)
  shared_preferences: ^2.2.3
  uuid: ^4.5.2
  timeago: ^3.7.1
  rxdart: ^0.28.0
  share_plus: ^12.0.1
  google_mlkit_language_id: ^0.13.0
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^20.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    # If you have specific folders for flags or other images, list them here too
    # - assets/flags/